"""Database-backed persistence for generated shopping lists.

Issue #65 (HIGH): the shopping list generated by ``POST
/shopping-list/generate`` used to live only in the Flask session cookie.
Cookies cap out at roughly 4KB, so large lists were silently truncated, and
because the cookie is scoped to a single browser, other household members
could not see a list generated by someone else.

:class:`ShoppingListStore` replaces that with DB-backed storage, following
the same connection-per-operation pattern as
:class:`~grocery_butler.recipe_store.RecipeStore` and
:class:`~grocery_butler.pantry_manager.PantryManager`: a fresh connection is
opened for each operation and closed when done, and ``init_db`` is invoked
once at construction time so the schema always exists before use.
"""

from __future__ import annotations

import json
from typing import TYPE_CHECKING

from grocery_butler.db import get_connection, init_db
from grocery_butler.models import IngredientCategory, ShoppingListItem

if TYPE_CHECKING:
    from grocery_butler.db.adapter import DatabaseConnection, DictRow


def _row_to_item(row: DictRow) -> ShoppingListItem:
    """Convert a ``shopping_list_items`` row into a ShoppingListItem model.

    ``from_meals`` is stored as JSON-encoded TEXT (see migration 005) and
    is decoded back into a real ``list[str]`` here so template checks such
    as ``item.from_meals == ['restock']`` work against a genuine list
    rather than a JSON string.

    Args:
        row: Row from the ``shopping_list_items`` table.

    Returns:
        ShoppingListItem model instance reconstructed from the row.
    """
    return ShoppingListItem(
        ingredient=row["ingredient"],
        quantity=row["quantity"],
        unit=row["unit"],
        category=IngredientCategory(row["category"]),
        search_term=row["search_term"] or "",
        from_meals=json.loads(row["from_meals"]),
    )


class ShoppingListStore:
    """Persistent storage for generated shopping lists.

    Each call to :meth:`save_list` creates a new ``shopping_lists`` row
    (the "generation") along with all of its ``shopping_list_items`` rows,
    in a single transaction. Lists are retrieved either by ID
    (:meth:`get_list`) or as the most recently generated list
    (:meth:`get_latest_list`), which is what the shopping list page reads
    from -- replacing the old per-browser session cookie.
    """

    def __init__(self, db_path: str) -> None:
        """Initialize the store and ensure the database schema exists.

        Args:
            db_path: Path to the SQLite database file, or a PostgreSQL URL.
        """
        self._db_path = db_path
        init_db(db_path)

    def _connect(self) -> DatabaseConnection:
        """Open a new database connection.

        Returns:
            Configured DatabaseConnection.
        """
        return get_connection(self._db_path)

    def save_list(self, items: list[ShoppingListItem]) -> int:
        """Persist a shopping list and all of its items in one transaction.

        Args:
            items: Shopping list items to persist.

        Returns:
            Database ID of the newly created shopping list.

        Raises:
            RuntimeError: If the INSERT unexpectedly fails to report a row
                ID (indicates an adapter/driver bug, not a user error).
        """
        conn = self._connect()
        try:
            list_id = self._insert_list(conn)
            self._insert_items(conn, list_id, items)
            conn.commit()
            return list_id
        finally:
            conn.close()

    @staticmethod
    def _insert_list(conn: DatabaseConnection) -> int:
        """Insert a new (empty) shopping_lists row.

        Args:
            conn: Active database connection.

        Returns:
            Database ID of the new shopping list.

        Raises:
            RuntimeError: If the INSERT does not report a row ID.
        """
        cursor = conn.execute("INSERT INTO shopping_lists DEFAULT VALUES")
        list_id = cursor.lastrowid
        if list_id is None:  # pragma: no cover
            msg = "INSERT into shopping_lists did not return a row ID"
            raise RuntimeError(msg)
        return list_id

    @staticmethod
    def _insert_items(
        conn: DatabaseConnection,
        list_id: int,
        items: list[ShoppingListItem],
    ) -> None:
        """Insert all item rows for a shopping list.

        Args:
            conn: Active database connection.
            list_id: ID of the parent shopping list.
            items: Shopping list items to persist.
        """
        for item in items:
            conn.execute(
                "INSERT INTO shopping_list_items "
                "(list_id, ingredient, quantity, unit, category,"
                " search_term, from_meals) VALUES (?, ?, ?, ?, ?, ?, ?)",
                (
                    list_id,
                    item.ingredient,
                    item.quantity,
                    item.unit.value,
                    item.category.value,
                    item.search_term,
                    json.dumps(item.from_meals),
                ),
            )

    def get_latest_list(self) -> list[ShoppingListItem]:
        """Return the items of the most recently saved shopping list.

        Returns:
            List of ShoppingListItem for the newest generation, or ``[]``
            if no shopping list has ever been saved.
        """
        conn = self._connect()
        try:
            row = conn.execute(
                "SELECT id FROM shopping_lists"
                " ORDER BY created_at DESC, id DESC LIMIT 1"
            ).fetchone()
            if row is None:
                return []
            return self._fetch_items(conn, row["id"])
        finally:
            conn.close()

    def get_list(self, list_id: int) -> list[ShoppingListItem]:
        """Return the items belonging to a specific shopping list.

        Args:
            list_id: Database ID of the shopping list.

        Returns:
            List of ShoppingListItem, or ``[]`` if ``list_id`` is unknown.
        """
        conn = self._connect()
        try:
            return self._fetch_items(conn, list_id)
        finally:
            conn.close()

    @staticmethod
    def _fetch_items(conn: DatabaseConnection, list_id: int) -> list[ShoppingListItem]:
        """Fetch and convert all item rows for a given list_id.

        Args:
            conn: Active database connection.
            list_id: Database ID of the shopping list.

        Returns:
            List of ShoppingListItem belonging to ``list_id``, in insertion
            order. Empty if the list has no items (or doesn't exist).
        """
        rows = conn.execute(
            "SELECT * FROM shopping_list_items WHERE list_id = ? ORDER BY id",
            (list_id,),
        ).fetchall()
        return [_row_to_item(row) for row in rows]
